# Generated by Django 3.2.4 on 2021-06-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='registration_date',
        ),
    ]
