# Generated by Django 3.2.4 on 2021-06-15 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_doctor_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date registered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_hour',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time registered'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='waiting_status',
            field=models.BooleanField(default=True),
        ),
    ]
